name: usecase
description: "A new Flutter package project."
version: 1.0.0
sdk: ">=3.0.0 <4.0.0"
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
